// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U-V8ff8YGsIDQmpKDSRJHJ_UVr4CCU4',
    appId: '1:374320105611:web:11b60944e65c5c4d856c8e',
    messagingSenderId: '374320105611',
    projectId: 'fruit-hub-183ac',
    authDomain: 'fruit-hub-183ac.firebaseapp.com',
    storageBucket: 'fruit-hub-183ac.firebasestorage.app',
    measurementId: 'G-FV1KTLHP6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhy7e6emMDbdO-0sxznD6UgGzg6jE5z6Q',
    appId: '1:374320105611:android:56234700e6817136856c8e',
    messagingSenderId: '374320105611',
    projectId: 'fruit-hub-183ac',
    storageBucket: 'fruit-hub-183ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8oswWR95D3adUYPXNzn4EphqUdTsP54',
    appId: '1:374320105611:ios:939b4e7f3fe99fe1856c8e',
    messagingSenderId: '374320105611',
    projectId: 'fruit-hub-183ac',
    storageBucket: 'fruit-hub-183ac.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8oswWR95D3adUYPXNzn4EphqUdTsP54',
    appId: '1:374320105611:ios:939b4e7f3fe99fe1856c8e',
    messagingSenderId: '374320105611',
    projectId: 'fruit-hub-183ac',
    storageBucket: 'fruit-hub-183ac.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2U-V8ff8YGsIDQmpKDSRJHJ_UVr4CCU4',
    appId: '1:374320105611:web:3791996b33a46a20856c8e',
    messagingSenderId: '374320105611',
    projectId: 'fruit-hub-183ac',
    authDomain: 'fruit-hub-183ac.firebaseapp.com',
    storageBucket: 'fruit-hub-183ac.firebasestorage.app',
    measurementId: 'G-C1PJDCHDNP',
  );
}
